declare const _default: {
    string: import("../interface").ExecuteValidator;
    method: import("../interface").ExecuteValidator;
    number: import("../interface").ExecuteValidator;
    boolean: import("../interface").ExecuteValidator;
    regexp: import("../interface").ExecuteValidator;
    integer: import("../interface").ExecuteValidator;
    float: import("../interface").ExecuteValidator;
    array: import("../interface").ExecuteValidator;
    object: import("../interface").ExecuteValidator;
    enum: import("../interface").ExecuteValidator;
    pattern: import("../interface").ExecuteValidator;
    date: import("../interface").ExecuteValidator;
    url: import("../interface").ExecuteValidator;
    hex: import("../interface").ExecuteValidator;
    email: import("../interface").ExecuteValidator;
    tel: import("../interface").ExecuteValidator;
    required: import("../interface").ExecuteValidator;
    any: import("../interface").ExecuteValidator;
};
export default _default;
