var locale = {
  locale: 'am_ET',
  today: 'ዛሬ',
  now: 'አሁን',
  backToToday: 'ወደ ዛሬ ተመለስ',
  ok: 'እሺ',
  clear: 'አንፃ',
  week: 'ሳምንት',
  month: 'ወር',
  year: 'ዓመት',
  timeSelect: 'ሰዓት ምረጥ',
  dateSelect: 'ቀን ምረጥ',
  weekSelect: 'ሳምንት ምረጥ',
  monthSelect: 'ወር ምረጥ',
  yearSelect: 'አመት ምረጥ',
  decadeSelect: 'አስርት አመታት ምረጥ',
  yearFormat: 'YYYY',
  dateFormat: 'D/M/YYYY',
  dayFormat: 'D',
  dateTimeFormat: 'D/M/YYYY HH:mm:ss',
  monthBeforeYear: true,
  previousMonth: 'ያለፈው ወር (PageUp)',
  nextMonth: 'ቀጣይ ወር (PageDown)',
  previousYear: 'ያለፈው ዓመት (Control + left)',
  nextYear: 'ቀጣይ ዓመት (Control + right)',
  previousDecade: 'ያለፈው አስርት ዓመት',
  nextDecade: 'ቀጣይ አስርት ዓመት',
  previousCentury: 'ያለፈው ክፍለ ዘመን',
  nextCentury: 'ቀጣይ ክፍለ ዘመን'
};
export default locale;